<?php
declare(strict_types=1);

/*
 * 	Constant definitions
 *
 *	@package	sync*gw
 *	@subpackage	Remote Operations (ROP) List and Encoding Protocol
 *	@copyright	(c) 2008 - 2023 Florian Daeumling, Germany. All right reserved
 * 	@license 	https://github.com/Toteph42/syncgw/blob/master/LICENSE
 */

namespace syncgw\mapi\rops;

class ropDefs {

	// [MS-OXCROPS] 2.2.2 The Table of RopIds
	const ROP_ID			 		= [
		'Release'									=> 0x01,
		'OpenFolder'								=> 0x02,
//		'OpenMessage'								=> 0x03,
//		'GetHierarchyTable'							=> 0x04,
//		'GetContentsTable'							=> 0x05,
//		'CreateMessage'								=> 0x06,
		'GetPropertiesSpecific'						=> 0x07,
//		'GetPropertiesAll'							=> 0x08,
//		'GetPropertiesList'							=> 0x09,
		'SetProperties'								=> 0x0a,
//		'DeleteProperties'							=> 0x0b,
//		'SaveChangesMessage'						=> 0x0c,
//		'RemoveAllRecipients'						=> 0x0d,
// 		'ModifyRecipients'							=> 0x0e,
//		'ReadRecipients'							=> 0x0f,
//		'ReloadCachedInformation'					=> 0x10,
// 		'SetMessageReadFlag'						=> 0x11,
//		'SetColumns'								=> 0x12,
//		'SortTable'									=> 0x13,
//		'Restrict'									=> 0x14,
//		'QueryRows'									=> 0x15,
//		'GetStatus'									=> 0x16,
//		'QueryPosition'								=> 0x17,
//		'SeekRow'									=> 0x18,
//		'SeekRowBookmark'							=> 0x19,
//		'SeekRowFractional'							=> 0x1a,
//		'CreateBookmark'							=> 0x1b,
		'CreateFolder'								=> 0x1c,
		'DeleteFolder'								=> 0x1d,
//		'DeleteMessages'							=> 0x1e,
//		'GetMessageStatus'							=> 0x1f,
//		'SetMessageStatus'							=> 0x20,
//		'GetAttachmentTable'						=> 0x21,
//		'OpenAttachment'							=> 0x22,
//		'CreateAttachment'							=> 0x23,
//		'DeleteAttachment'							=> 0x24,
//		'SaveChangesAttachment'						=> 0x25,
//		'SetReceiveFolder'							=> 0x26,
		'GetReceiveFolder'							=> 0x27,
//		'RegisterNotification'						=> 0x29,
//		'Notify'									=> 0x2a,
//		'OpenStream'								=> 0x2b,
//		'ReadStream'								=> 0x2c,
//		'WriteStream'								=> 0x2d,
//		'SeekStream'								=> 0x2e,
//		'SetStreamSize'								=> 0x2f,
//		'SetSearchCriteria'							=> 0x30,
//		'GetSearchCriteria'							=> 0x31,
//		'SubmitMessage'								=> 0x32,
//		'MoveCopyMessages'							=> 0x33,
//		'AbortSubmit'								=> 0x34,
		'MoveFolder'								=> 0x35,
//		'CopyFolder'								=> 0x36,
//		'QueryColumnsAll'							=> 0x37,
//		'Abort'										=> 0x38,
//		'CopyTo'									=> 0x39,
//		'CopyToStream'								=> 0x3a,
//		'CloneStream'								=> 0x3b,
//		'GetPermissionsTable'						=> 0x3e,
//		'GetRulesTable'								=> 0x3f,
//		'ModifyPermissions'							=> 0x40,
//		'ModifyRules'								=> 0x41,
//		'GetOwningServers'							=> 0x42,
		'LongTermIdFromId'							=> 0x43,
//		'IdFromLongTermId'							=> 0x44,
		'PublicFolderIsGhosted'						=> 0x45,
//		'OpenEmbeddedMessage'						=> 0x46,
//		'SetSpooler'								=> 0x47,
//		'SpoolerLockMessage'						=> 0x48,
		'GetAddressTypes'							=> 0x49,
//		'TransportSend'								=> 0x4a,
//		'FastTransferSourceCopyMessages'			=> 0x4b,
//		'FastTransferSourceCopyFolder'				=> 0x4c,
//		'FastTransferSourceCopyTo'					=> 0x4d,
		'FastTransferSourceGetBuffer'				=> 0x4e,
//		'FindRow'									=> 0x4f,
//		'Progress'									=> 0x50,
//		'TransportNewMail'							=> 0x51,
//		'GetValidAttachments'						=> 0x52,
//		'FastTransferDestinationConfigure'			=> 0x53,
//		'FastTransferDestinationPutBuffer'			=> 0x54,
//		'GetNamesFromPropertyIds'					=> 0x55,
		'GetPropertyIdsFromNames'					=> 0x56,
//		'UpdateDeferredActionMessages'				=> 0x57,
//		'EmptyFolder'								=> 0x58,
//		'ExpandRow'									=> 0x59,
//		'CollapseRow'								=> 0x5a,
//		'LockRegionStream'							=> 0x5b,
//		'UnlockRegionStream'						=> 0x5c,
//		'CommitStream'								=> 0x5d,
//		'GetStreamSize'								=> 0x5e,
//		'QueryNamedProperties'						=> 0x5f,
//		'GetPerUserLongTermIds'						=> 0x60,
//		'GetPerUserGuid'							=> 0x61,
//		'ReadPerUserInformation'					=> 0x63,
//		'WritePerUserInformation'					=> 0x64,
//		'SetReadFlags'								=> 0x66,
//		'CopyProperties'							=> 0x67,
//		'GetReceiveFolderTable'						=> 0x68,
//		'FastTransferSourceCopyProperties'			=> 0x69,
//		'GetCollapseState'							=> 0x6b,
//		'SetCollapseState'							=> 0x6c,
//		'GetTransportFolder'						=> 0x6d,
//		'Pending'									=> 0x6e,
//		'OptionsData'								=> 0x6f,
		'SynchronizationConfigure'					=> 0x70,
//		'SynchronizationImportMessageChange'		=> 0x72,
//		'SynchronizationImportHierarchyChange'		=> 0x73,
//		'SynchronizationImportDeletes'				=> 0x74,
		'SynchronizationUploadStateStreamBegin'		=> 0x75,
		'SynchronizationUploadStateStreamContinue'	=> 0x76,
		'SynchronizationUploadStateStreamEnd'		=> 0x77,
//		'SynchronizationImportMessageMove'			=> 0x78,
//		'SetPropertiesNoReplicate'					=> 0x79,
//		'DeletePropertiesNoReplicate'				=> 0x7a,
		'GetLocalReplicaIds'						=> 0x7f,
//		'SynchronizationImportReadStateChanges'		=> 0x80,
//		'ResetTable'								=> 0x81,
//		'SynchronizationGetTransferState'			=> 0x82,
//		'TellVersion'								=> 0x86,
//		'FreeBookmark'								=> 0x89,
//		'WriteAndCommitStream'						=> 0x90,
//		'HardDeleteMessages'						=> 0x91,
//		'HardDeleteMessagesAndSubfolders'			=> 0x92,
//		'SetLocalReplicaMidsetDeleted'				=> 0x93,
//		'Backoff'									=> 0xf9,
		'Logon'			 							=> 0xfe,
//		'BufferTooSmall'							=> 0xff,
	];

	// [MS-OXCFOLD]	2.2.1.2.1 RopCreateFolder ROP Request Buffer
	const FOLDER_TYP				= [
		'Generic'									=> 1,
		'Search'									=> 2,
	];

	// [MS-OXCFOLD]	2.2.1.3.1 RopDeleteFolder ROP Request Buffer
	const FOLDER_DEL				= [
		'Messages'									=> 0x01,
		'Folders'									=> 0x02,
		'HardDelete'								=> 0x04,
	];

}

?>